const images = {
  bkgSplash: require('@assets/images/bkgSplash.png'),
  imgLogo: require('@assets/images/imgLogo.png'),
  imgAvatar: require('@assets/images/imgAvatar.png'),
  imgLoginLogo: require('@assets/images/imgLoginLogo.png'),
  imgForgotPwdBg: require('@assets/images/ForgotPasswordBg.png'),
  imgCampLogoBg: require('@assets/images/CAMPID_LOGO_BG.png'),
  imgSignupBg: require('@assets/images/imgRegisterBg.png'),
  imgEarth: require('@assets/images/imgEarth.png'),
  noImage: require('@assets/images/noImage.png'),
  SignUpBg: require('@assets/images/SignUpBg.png'),
  selectBg: require('@assets/images/selectBg.png'),
  selectSkillBg: require('@assets/images/selectSkillBg.png'),
  registerSkillBg: require('@assets/images/registerSkillBg.png'),
  registerExpBg: require('@assets/images/imgRegisterExpBg.png'),
  registerDoneBg: require('@assets/images/imgRegisterDoneBg.png'),
  myCamp1: require('@assets/images/myCamp1.png'),
  myCamp2: require('@assets/images/myCamp2.png'),
  myCamp3: require('@assets/images/myCamp3.png'),
  imgLeftBtn: require('@assets/images/leftBtn.png'),
  imgRightBtn: require('@assets/images/rightBtn.png'),
  imgAddBtn: require('@assets/images/imgAddButton.png'),
  rateBar: require('@assets/images/rateBar.png'),
  downArrow: require('@assets/images/down_arrow.png'),
  sportsID: require('@assets/images/SPORTS_ID.png'),         
  campID: require('@assets/images/campID.png'),                
  rgThumbnail: require('@assets/images/rgThumbnail.png'),
  pdf: require('@assets/images/pdf.png'),
  calendar: require('@assets/images/calendar.png'),
  person: require('@assets/images/person.png'),
  card: require('@assets/images/card.png'),
  serchBar: require('@assets/images/serchBar.png'),
  checked: require('@assets/images/checked.png'),
  unchecked: require('@assets/images/unchecked.png'),
  subunchecked: require('@assets/images/subunchecked.png'),
  gallery1: require('@assets/images/gallery1.png'),
  gallery2: require('@assets/images/gallery2.png'),
  gallery3: require('@assets/images/gallery3.png'),
  gallery4: require('@assets/images/gallery4.png'),
  news1: require('@assets/images/News1.png'),
  news2: require('@assets/images/News2.png'),

  imgListBg: require('@assets/images/imgListBg.png'),
  item1: require('@assets/images/item1.png'),
  item2: require('@assets/images/item2.png'),
  item3: require('@assets/images/item3.png'),
  item4: require('@assets/images/item4.png'),
  item5: require('@assets/images/item5.png'),
  item6: require('@assets/images/item6.png'),
  item7: require('@assets/images/item7.png'),
  item8: require('@assets/images/item8.png'),

  imgMan1: require('@assets/images/imgMan1.png'),
  imgMan2: require('@assets/images/imgMan2.png'),
  imgMan3: require('@assets/images/imgMan3.png'),
  imgMan4: require('@assets/images/imgMan4.png'),
  imgMan5: require('@assets/images/imgMan5.png'),
  imgMan6: require('@assets/images/imgMan6.png'),
  imgMan7: require('@assets/images/imgMan7.png'),
  imgMan8: require('@assets/images/imgMan3.png'),
  imgMan9: require('@assets/images/imgAvatar.png'),
  
};

export default images;
